#pragma once

#include "sdkconfig.h"

#define STR_HAS_UART (CONFIG_STR_UART0 || CONFIG_STR_UART1 || CONFIG_STR_UART2)

#define STR_MASTER_HAS_UART (CONFIG_STR_MASTER_UART0 ||\
							CONFIG_STR_MASTER_UART1 ||\
							CONFIG_STR_MASTER_UART2)

#define STR_SLAVE_HAS_UART (CONFIG_STR_SLAVE_UART0 ||\
							CONFIG_STR_SLAVE_UART1 ||\
							CONFIG_STR_SLAVE_UART2)

#define STR_HAS_ESPNOW CONFIG_STR_ESPNOW

#if !STR_HAS_UART && !STR_HAS_ESPNOW
// #error "STR has no communication core"
#endif

#define HAS_LED_STRIP (CONFIG_STR_HAS_LED_STRIP_0 || \
						CONFIG_STR_HAS_LED_STRIP_1 || \
						CONFIG_STR_HAS_LED_STRIP_2 || \
						CONFIG_STR_HAS_LED_STRIP_3)

#define LS_0_PIN CONFIG_STR_LED_STRIP_0_PIN
#define LS_0_LEN CONFIG_STR_LED_STRIP_0_DATA_LEN

#define LS_1_PIN CONFIG_STR_LED_STRIP_1_PIN
#define LS_1_LEN CONFIG_STR_LED_STRIP_1_DATA_LEN

#define LS_2_PIN CONFIG_STR_LED_STRIP_2_PIN
#define LS_2_LEN CONFIG_STR_LED_STRIP_2_DATA_LEN

#define LS_3_PIN CONFIG_STR_LED_STRIP_3_PIN
#define LS_3_LEN CONFIG_STR_LED_STRIP_3_DATA_LEN

#ifndef CONFIG_STR_MASTER_ESPNOW
#define CONFIG_STR_MASTER_ESPNOW 0
#endif

#ifndef CONFIG_STR_SLAVE_ESPNOW
#define CONFIG_STR_SLAVE_ESPNOW 0
#endif

#define NB_ESPNOW_CTR CONFIG_STR_NB_SLAVE * CONFIG_STR_SLAVE_ESPNOW + CONFIG_STR_MASTER_ESPNOW

#ifndef CONFIG_STR_MASTER_UART0
#define CONFIG_STR_MASTER_UART0 0
#endif
#ifndef CONFIG_STR_MASTER_UART1
#define CONFIG_STR_MASTER_UART1 0
#endif
#ifndef CONFIG_STR_MASTER_UART2
#define CONFIG_STR_MASTER_UART2 0
#endif

#ifndef CONFIG_STR_SLAVE_UART0
#define CONFIG_STR_SLAVE_UART0 0
#endif
#ifndef CONFIG_STR_SLAVE_UART1
#define CONFIG_STR_SLAVE_UART1 0
#endif
#ifndef CONFIG_STR_SLAVE_UART2
#define CONFIG_STR_SLAVE_UART2 0
#endif

#define NB_UART_CTR (CONFIG_STR_MASTER_UART0 || CONFIG_STR_SLAVE_UART0)\
					+ (CONFIG_STR_MASTER_UART1 || CONFIG_STR_SLAVE_UART1)\
					+ (CONFIG_STR_MASTER_UART2 || CONFIG_STR_SLAVE_UART2)

#define STRIP_FIRST_COMMA(comma, ...) __VA_ARGS__
